name: hackaton
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flex_color_scheme: ^7.0.5
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^1.7.1
  flutter_local_notifications: ^14.0.0+1
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  go_router: ^6.5.9
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+4
  json_annotation: ^4.8.0
  loader_overlay: ^2.2.0
  responsive_framework: ^1.0.0
  riverpod_annotation: ^2.0.1
  timezone: ^0.9.2
  transparent_image: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
